inouefood/oh-natto

natto.xcodeproj/project.pbxproj, natto/Info.plist
=> feat: Add bundle version

natto.xcodeproj/project.pbxproj, natto/Extension/SKPhysicsBody+Addition.swift, natto/Extension/SKSpriteNode+Addition.swift, natto/Game/MixScene.swift, natto/PullNatto/PullNattoScene.swift
* initializerを使った際に画像が表示されない問題の解決
* ohashiとnattoなどを自作のinitializerで初期化するようにした
=> refactor: make initializer works correctly

natto/GameScene.swift
* UserDefaultsを使ってインストール後の初回のみチュートリアルを表示するようにした
* `showTutorial()`をタップ入力以外でも使用するために`showTutorialTapped()`を追加し分離
かなり無理矢理な実装になっている気がします
=> Feature: Show tutorial if it is first session

natto.xcodeproj/project.pbxproj, natto/Common/Constant.swift, natto/Scene/Game/MixScene.swift, natto/Scene/PullNatto/PullNattoScene.swift
=> feat: Add constant

.gitignore
=> fix: Changed gitignore

natto.xcodeproj/project.pbxproj, natto/Extension/CGMutablePath+Addition.swift, natto/Extension/SKShapeNode+Addition.swift, natto/Scene/Game/MixScene.swift
* MixSceneのaddStickyLine関数内のリファクタ
* リファクタのためCGMutablePathと，SKShapeNodeのExtensionを追加
=> refactor: Refactor addStickyLine func

natto.xcodeproj/project.pbxproj
=> feat: Change Swift version

natto.xcodeproj/project.pbxproj, natto/Info.plist
=> Feature/bump up version1.3.0 2

natto/Info.plist
=> feat: Add app version

natto/Scene/Mix/MixModel.swift, natto/Scene/Mix/MixPresenter.swift, natto/Scene/Mix/MixScene.swift
* MixSceneのdidBegin関数内で行なっていた衝突判定をリファクタ
=> Refactor: MixScene didbegin func

natto/Scene/Mix/MixScene.swift, natto/Scene/PullNatto/PullNattoPresenter.swift, natto/Scene/PullNatto/PullNattoScene.swift
* nattoの衝突判定の円など、固定数を使っていた部分を、比率で計算するよう修正
=> fix: fix physicsbody size

natto.xcodeproj/project.pbxproj, natto/Extension/SKScene+Addition.swift, natto/Scene/PullNatto/PullNattoScene.swift, natto/Scene/Result/ResultScene.swift, natto/Scene/Title/TitleScene.swift
* titleLabelが画面外に出せてしまうバグを修正
* SKSceneのextensionを作成
=> fix: Fixed title label y position range

natto/Info.plist
=> feat: Add app version v1.3.2

natto/Extension/SKScene+Addition.swift, natto/Info.plist, natto/Scene/Description/DescriptionViewController.swift, natto/Scene/Mix/MixScene.swift, natto/Scene/PullNatto/PullNattoScene.swift, natto/Scene/Result/ResultScene.swift, natto/Scene/Title/TitleScene.swift
* 全体的なリファクタ
* 1.3.2がなぜかリリース失敗するので1.3.3で試したい
=> Fixed mix scene logic

natto.xcodeproj/project.pbxproj, natto/Common/Constant.swift, natto/Extension/Entity/ObjectPosition.swift, natto/Extension/Entity/ObjectSize.swift, natto/Scene/PullNatto/PullNattoModel.swift, natto/Scene/PullNatto/PullNattoPresenter.swift, natto/Scene/PullNatto/PullNattoScene.swift
=> Refactor eat logic

natto/AppDelegate.swift
=> feat: Add local notification

natto/Info.plist
=> feat: Bunp up version 1.4.1

natto.xcodeproj/project.pbxproj, natto/Info.plist
=> feat: Bump up version

natto/Extension/SKScene+Addition.swift, natto/Scene/Mix/MixScene.swift
* mixSceneの豆のサイズを端末比率で変更するように修正しました
=> refactor:MixSceneの豆サイズを修正しました

natto/Scene/Mix/MixScene.swift
=> feature: 納豆を混ぜた時のfeedbackを追加しました

natto.xcodeproj/project.pbxproj, natto/Extension/UIViewController+Addition.swift, natto/Scene/Title/TitleScene.swift, natto/Store/UserStore.swift, natto/View/Result/ResultViewController.swift, natto/View/Result/ResultViewController.xib, natto/View/Select/SelectViewController.swift, natto/View/Select/SelectViewController.xib, natto/View/Store/StoreViewController.swift, natto/View/Store/StoreViewController.xib, natto/View/TotalEat/TotalEatViewController.swift, natto/View/TotalEat/TotalEatViewController.xib
* Result画面にアイテム購入ができる画面を追加しました
=> Result画面にアイテム購入ができる画面を追加

natto/Scene/Title/TitleScene.swift
タイトル画面での納豆の大きさが固定だったものを，画面サイズをもとに計算するようにしました。
=> TitleSceneでのNattoの大きさを画面サイズごとに変更

natto/View/Main/Description/DescriptionViewController.swift, natto/View/Main/Description/DescriptionViewController.xib
=> PageControlのタップを禁止しました

natto.xcodeproj/project.pbxproj, natto/Extension/Entity/OwnedItem.swift, natto/Scene/Title/TitleScene.swift, natto/Store/UserStore.swift, natto/View/Main/EquipmentSelect/EquipmentSelectViewController.swift, natto/View/Main/EquipmentSelect/ToppingSelect/ToppingSelectViewController.swift, natto/View/Main/EquipmentSelect/ToppingSelect/ToppingSelectViewController.xib, natto/View/Result/Select/Store/StoreViewController.swift
* トッピング選択部分を本番用のデータに置き換えました
* 購入選択スタートで実際にデータの増減を繋ぎ込みました
=> トッピング選択部分を本番用のデータに置き換える

natto/Info.plist
=> ダークモードを禁止しました

natto/View/Result/Select/SelectViewController.swift, natto/View/Result/Select/SelectViewController.xib
* outlet接続がうまくいっていなかったので修正しました
=> Resultnシェア画面が機能していないバグの修正

natto.xcodeproj/project.pbxproj, natto/Extension/UIImage+Addition.swift, natto/View/Result/BestScore/BestScoreViewController.swift, natto/View/Result/BestScore/BestScoreViewController.xib, natto/View/Result/ResultViewController.swift
=> SNSでベストスコアの画像を共有できるようにしました

natto/Extension/SKSpriteNode+Addition.swift, natto/Scene/PullNatto/PullNattoScene.swift
=> トッピングを使ってゲームを遊べるようにする

natto/View/Main/Description/DescriptionViewController.swift, natto/View/Main/Description/DescriptionViewController.xib
* チュートリアル画面のiPad出し分けました
* 機能が増えたことによる説明画面の追加
=> チュートリアル画面のiPad出し分け

natto.xcodeproj/project.pbxproj, natto/Extension/UIColor+Addition.swift, natto/View/Main/Description/DescriptionViewController.swift, natto/View/Result/ResultViewController.swift
=> アプリで使用する色を定義するクラスを追加

natto.xcodeproj/project.pbxproj, natto/Assets.xcassets/AppColor/Contents.json, natto/Assets.xcassets/AppColor/background.colorset/Contents.json, natto/Assets.xcassets/AppColor/button.colorset/Contents.json, natto/Assets.xcassets/AppColor/gamePlayBackground.colorset/Contents.json, natto/Assets.xcassets/AppColor/tutorial.colorset/Contents.json, natto/Assets.xcassets/AppColor/white.colorset/Contents.json, natto/Common/AppColor.swift, natto/Extension/UIColor+Addition.swift, natto/Scene/Mix/MixScene.swift, natto/Scene/PullNatto/PullNattoScene.swift, natto/Scene/Result/ResultScene.swift, natto/Scene/Title/TitleScene.swift, natto/View/Main/Description/DescriptionViewController.swift, natto/View/Main/Description/customView/DescriptionView.xib, natto/View/Main/Setting/SettingViewController.xib, natto/View/Main/ToppingSelect/ToppingSelectViewController.xib, natto/View/Result/BestScore/BestScoreViewController.swift, natto/View/Result/ResultViewController.swift, natto/View/Result/Select/TotalEat/TotalEatViewController.swift, natto/View/Result/customView/ShareButton.swift
=> oh!natto!用のカラーアセットの追加と設定

natto/View/Result/ResultViewController.swift, natto/View/Result/ResultViewController.xib, natto/View/Result/Select/SelectViewController.swift, natto/View/Result/Select/SelectViewController.xib
* Result画面でスクリーンショットを共有できるようにしました
=> Result画面の共有でスコア部分をスクショで投稿できるようにする

natto/View/Main/NattoViewController.swift
* ゲーム中のstatusBarをhiddenに切り替えました
=> ゲーム中のstatusBarをhiddenに切り替えました

natto/View/Result/BestScore/BestScoreViewController.swift
*  UIActivityViewControllerを初めて開く時にめちゃくちゃ重かったので修正
* parthcleが問題かと思い止めたが変わらず
=> 共通画面のパフォーマンス修正

natto/Assets.xcassets/AppColor/gamePlayBackground.colorset/Contents.json
* アセットのgamePlayBackgroundのcolosetの値を変更しました
=> feat:ゲームプレイ画面の背景色をわずかに明るくしました

natto.xcodeproj/project.pbxproj
=> version_v2.0.0

natto.xcodeproj/project.pbxproj
=> パッチリリース用のバージョンアップ
